export * from './Nav'
export * from './Photos'
export * from './NotFound'
export * from './Header'
export * from './Searchform'
export * from './Photo'
export * from './Error'
export * from './Loading'